"use strict";

/*
 * CONSTITUTION 365
 * Editorial Quality Checker
 *
 * Purpose:
 * Check whether a generated lesson is:
 * - clear
 * - sufficiently detailed
 * - genuinely useful
 * - naturally written in Telugu
 * - non-repetitive
 * - example-driven
 * - appropriate for ordinary people
 * - free from obvious exam-note / AI-output patterns
 *
 * IMPORTANT:
 * This is a deterministic quality gate.
 *
 * It does NOT replace human/editorial review.
 * It identifies obvious weak generations so that the pipeline
 * can automatically regenerate them.
 */

const {
  LESSON_FIELDS
} = require("./validate-day");


/*
 * ------------------------------------------------------------
 * CONFIGURATION
 * ------------------------------------------------------------
 */

const MIN_TOTAL_CHARACTERS = 900;
const MAX_TOTAL_CHARACTERS = 30000;

const MIN_FIELD_CHARACTERS = {
  opening: 80,
  explanation: 180,
  why_it_matters: 100,
  how_it_works: 100,
  real_life_example: 100,
  simple_comparison: 60,
  common_misunderstanding: 60,
  what_it_means_for_me: 80,
  takeaway: 50
};

const MIN_TELUGU_RATIO = 0.45;

const MAX_REPEATED_SENTENCE_COUNT = 1;

const MAX_GENERIC_PHRASE_COUNT = 2;


/*
 * ------------------------------------------------------------
 * GENERIC / LOW-VALUE PHRASES
 * ------------------------------------------------------------
 *
 * These are not always wrong.
 * They become a problem when a lesson repeatedly relies on them.
 */

const GENERIC_PHRASES = [
  "ఈ విషయం చాలా ముఖ్యమైనది",
  "మనందరికీ ఇది చాలా ముఖ్యమైనది",
  "మన జీవితంలో ఇది చాలా ముఖ్యమైనది",
  "ఇది చాలా ప్రాముఖ్యత కలిగినది",
  "మనము దీనిని అర్థం చేసుకోవాలి",
  "ఇది మనకు చాలా ఉపయోగకరం",
  "సులభంగా చెప్పాలంటే",
  "మొత్తానికి",
  "చివరగా చెప్పాలంటే",
  "ఈ విధంగా మనం అర్థం చేసుకోవచ్చు"
];


/*
 * ------------------------------------------------------------
 * EXAM-STYLE PHRASES
 * ------------------------------------------------------------
 */

const EXAM_STYLE_PHRASES = [
  "పరీక్షలో",
  "పరీక్షలకు",
  "ముఖ్యమైన పాయింట్",
  "గుర్తుంచుకోండి",
  "ముఖ్యమైన అంశాలు",
  "ఎగ్జామ్",
  "mcq",
  "బహుళ ఎంపిక",
  "కాంపిటేటివ్",
  "పోటీ పరీక్ష"
];


/*
 * ------------------------------------------------------------
 * AI / META PHRASES
 * ------------------------------------------------------------
 */

const AI_META_PHRASES = [
  "as an ai",
  "as an artificial intelligence",
  "language model",
  "chatgpt",
  "openai",
  "groq",
  "generated by",
  "here is the answer",
  "here is the json"
];


/*
 * ------------------------------------------------------------
 * HELPER FUNCTIONS
 * ------------------------------------------------------------
 */

function isObject(value) {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value)
  );
}


function normalize(text) {
  if (typeof text !== "string") {
    return "";
  }

  return text
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}


function countOccurrences(text, phrase) {
  if (
    typeof text !== "string" ||
    !phrase
  ) {
    return 0;
  }

  const source = text.toLowerCase();
  const target = phrase.toLowerCase();

  let count = 0;
  let position = 0;

  while (true) {
    const index =
      source.indexOf(target, position);

    if (index === -1) {
      break;
    }

    count++;

    position =
      index + target.length;
  }

  return count;
}


function countTeluguCharacters(text) {
  if (typeof text !== "string") {
    return 0;
  }

  const matches =
    text.match(/[\u0C00-\u0C7F]/gu);

  return matches
    ? matches.length
    : 0;
}


function countLetterCharacters(text) {
  if (typeof text !== "string") {
    return 0;
  }

  const matches =
    text.match(/[A-Za-z\u0C00-\u0C7F]/gu);

  return matches
    ? matches.length
    : 0;
}


function teluguRatio(text) {
  const total =
    countLetterCharacters(text);

  if (total === 0) {
    return 0;
  }

  return (
    countTeluguCharacters(text) /
    total
  );
}


function splitSentences(text) {
  if (typeof text !== "string") {
    return [];
  }

  return text
    .split(/[.!?।!?]+/u)
    .map(item => normalize(item))
    .filter(Boolean);
}


function getDuplicateSentences(text) {
  const sentences =
    splitSentences(text);

  const counts = new Map();

  for (const sentence of sentences) {
    counts.set(
      sentence,
      (counts.get(sentence) || 0) + 1
    );
  }

  return [...counts.entries()]
    .filter(
      ([, count]) =>
        count > MAX_REPEATED_SENTENCE_COUNT
    )
    .map(
      ([sentence, count]) => ({
        sentence,
        count
      })
    );
}


function countParagraphs(text) {
  if (typeof text !== "string") {
    return 0;
  }

  return text
    .split(/\n\s*\n/u)
    .map(item => item.trim())
    .filter(Boolean)
    .length;
}


function countEnglishWords(text) {
  if (typeof text !== "string") {
    return 0;
  }

  const matches =
    text.match(/\b[A-Za-z]{2,}\b/g);

  return matches
    ? matches.length
    : 0;
}


function addError(errors, message) {
  errors.push(message);
}


function addWarning(warnings, message) {
  warnings.push(message);
}


/*
 * ------------------------------------------------------------
 * SECTION 1
 * BASIC LESSON CHECK
 * ------------------------------------------------------------
 */

function checkLessonStructure(
  generated,
  errors,
  warnings
) {
  if (!isObject(generated.lesson)) {
    addError(
      errors,
      "lesson is missing or is not an object."
    );

    return;
  }

  for (const field of LESSON_FIELDS) {
    const value =
      generated.lesson[field];

    if (
      typeof value !== "string" ||
      !value.trim()
    ) {
      addError(
        errors,
        `lesson.${field} is empty.`
      );

      continue;
    }

    const length =
      value.trim().length;

    const minimum =
      MIN_FIELD_CHARACTERS[field] || 40;

    if (length < minimum) {
      addError(
        errors,
        `lesson.${field} is too short (${length} characters; minimum ${minimum}).`
      );
    }

    if (countParagraphs(value) === 0) {
      addWarning(
        warnings,
        `lesson.${field} has no paragraph separation.`
      );
    }
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 2
 * TOTAL CONTENT DEPTH
 * ------------------------------------------------------------
 */

function checkOverallLength(
  generated,
  errors,
  warnings
) {
  if (!isObject(generated.lesson)) {
    return;
  }

  const total =
    LESSON_FIELDS.reduce(
      (sum, field) =>
        sum +
        (
          typeof generated.lesson[field] === "string"
            ? generated.lesson[field].trim().length
            : 0
        ),
      0
    );

  if (total < MIN_TOTAL_CHARACTERS) {
    addError(
      errors,
      `Lesson is too short overall (${total} characters; minimum ${MIN_TOTAL_CHARACTERS}).`
    );
  }

  if (total > MAX_TOTAL_CHARACTERS) {
    addWarning(
      warnings,
      `Lesson is unusually long (${total} characters).`
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 3
 * TELUGU QUALITY
 * ------------------------------------------------------------
 */

function checkTelugu(
  generated,
  errors,
  warnings
) {
  if (!isObject(generated.lesson)) {
    return;
  }

  const combined =
    LESSON_FIELDS
      .map(field =>
        generated.lesson[field] || ""
      )
      .join("\n");

  const ratio =
    teluguRatio(combined);

  if (ratio < MIN_TELUGU_RATIO) {
    addError(
      errors,
      `Telugu character ratio is too low (${(ratio * 100).toFixed(1)}%).`
    );
  }

  const englishWords =
    countEnglishWords(combined);

  /*
   * English terminology is not automatically wrong.
   * We only warn when there is an unusually high amount.
   */

  if (englishWords > 35) {
    addWarning(
      warnings,
      `Lesson contains many English words (${englishWords}).`
    );
  }

  /*
   * Detect obvious translation-like constructions.
   */

  const translationPatterns = [
    "ఇది అంటే ఏమిటంటే",
    "దీనిని ఇలా నిర్వచించవచ్చు",
    "ఈ సందర్భంలో",
    "పై విధంగా",
    "క్రింది విధంగా"
  ];

  let translationPatternCount = 0;

  for (const phrase of translationPatterns) {
    translationPatternCount +=
      countOccurrences(
        combined,
        phrase
      );
  }

  if (translationPatternCount >= 5) {
    addWarning(
      warnings,
      "Repeated formal/translation-like Telugu constructions detected."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 4
 * REAL-LIFE EXAMPLE
 * ------------------------------------------------------------
 */

function checkRealLifeExample(
  generated,
  errors,
  warnings
) {
  const text =
    generated.lesson &&
    generated.lesson.real_life_example;

  if (
    typeof text !== "string" ||
    !text.trim()
  ) {
    addError(
      errors,
      "A real-life example is required."
    );

    return;
  }

  /*
   * A useful example normally has some concrete context.
   */

  const contextualTerms = [
    "పాఠశాల",
    "విద్యార్థి",
    "కుటుంబం",
    "గ్రామం",
    "పట్టణం",
    "పని",
    "ఉద్యోగం",
    "ప్రభుత్వం",
    "ఆసుపత్రి",
    "పోలీసు",
    "కోర్టు",
    "ఎన్నిక",
    "ఓటు",
    "రోడ్డు",
    "కార్యాలయం",
    "వ్యాపారం",
    "రైతు",
    "కార్మికుడు",
    "ప్రజలు",
    "ఇల్లు",
    "సమాజం",
    "ఆన్‌లైన్",
    "ఫోన్"
  ];

  const hasContext =
    contextualTerms.some(
      term =>
        text.includes(term)
    );

  if (!hasContext) {
    addWarning(
      warnings,
      "Real-life example does not contain an obvious everyday context."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 5
 * COMMON MISUNDERSTANDING
 * ------------------------------------------------------------
 */

function checkMisunderstanding(
  generated,
  errors,
  warnings
) {
  const text =
    generated.lesson &&
    generated.lesson.common_misunderstanding;

  if (
    typeof text !== "string" ||
    !text.trim()
  ) {
    addError(
      errors,
      "common_misunderstanding is required."
    );

    return;
  }

  const correctionIndicators = [
    "కాదు",
    "అర్థం కాదు",
    "అలా కాదు",
    "తప్పుగా",
    "అపోహ",
    "అవసరం లేదు",
    "అనగా కాదు",
    "అర్థం చేసుకోకూడదు"
  ];

  const hasCorrection =
    correctionIndicators.some(
      term =>
        text.includes(term)
    );

  if (!hasCorrection) {
    addWarning(
      warnings,
      "common_misunderstanding does not clearly appear to correct a misconception."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 6
 * TAKEAWAY
 * ------------------------------------------------------------
 */

function checkTakeaway(
  generated,
  errors,
  warnings
) {
  const text =
    generated.lesson &&
    generated.lesson.takeaway;

  if (
    typeof text !== "string" ||
    !text.trim()
  ) {
    addError(
      errors,
      "takeaway is required."
    );

    return;
  }

  if (text.trim().length < 50) {
    addWarning(
      warnings,
      "Takeaway is very short."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 7
 * REPETITION
 * ------------------------------------------------------------
 */

function checkRepetition(
  generated,
  errors,
  warnings
) {
  if (!isObject(generated.lesson)) {
    return;
  }

  const combined =
    LESSON_FIELDS
      .map(field =>
        generated.lesson[field] || ""
      )
      .join("\n");

  const duplicates =
    getDuplicateSentences(
      combined
    );

  if (duplicates.length > 0) {
    for (const item of duplicates.slice(0, 5)) {
      addError(
        errors,
        `Repeated sentence detected ${item.count} times: "${item.sentence}"`
      );
    }
  }

  /*
   * Check repeated phrases across sections.
   */

  const normalizedFields =
    LESSON_FIELDS.map(
      field => ({
        field,
        text: normalize(
          generated.lesson[field]
        )
      })
    );

  for (
    let i = 0;
    i < normalizedFields.length;
    i++
  ) {
    for (
      let j = i + 1;
      j < normalizedFields.length;
      j++
    ) {
      const first =
        normalizedFields[i];

      const second =
        normalizedFields[j];

      if (
        first.text.length > 100 &&
        second.text.length > 100 &&
        (
          first.text.includes(
            second.text
          ) ||
          second.text.includes(
            first.text
          )
        )
      ) {
        addWarning(
          warnings,
          `Possible repeated content between lesson.${first.field} and lesson.${second.field}.`
        );
      }
    }
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 8
 * GENERIC CONTENT
 * ------------------------------------------------------------
 */

function checkGenericContent(
  generated,
  errors,
  warnings
) {
  if (!isObject(generated.lesson)) {
    return;
  }

  const combined =
    LESSON_FIELDS
      .map(field =>
        generated.lesson[field] || ""
      )
      .join("\n");

  let genericCount = 0;

  for (const phrase of GENERIC_PHRASES) {
    genericCount +=
      countOccurrences(
        combined,
        phrase
      );
  }

  if (
    genericCount >
    MAX_GENERIC_PHRASE_COUNT
  ) {
    addWarning(
      warnings,
      `Generic filler-style phrases appear frequently (${genericCount}).`
    );
  }

  /*
   * If the lesson is dominated by generic language,
   * reject it.
   */

  if (
    genericCount >= 6
  ) {
    addError(
      errors,
      "Lesson appears to rely too heavily on generic filler language."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 9
 * EXAM STYLE
 * ------------------------------------------------------------
 */

function checkExamStyle(
  generated,
  errors,
  warnings
) {
  if (!isObject(generated.lesson)) {
    return;
  }

  const combined =
    LESSON_FIELDS
      .map(field =>
        generated.lesson[field] || ""
      )
      .join("\n")
      .toLowerCase();

  let count = 0;

  for (const phrase of EXAM_STYLE_PHRASES) {
    if (
      combined.includes(
        phrase.toLowerCase()
      )
    ) {
      count++;
    }
  }

  if (count > 0) {
    addError(
      errors,
      "Exam-oriented language detected. Constitution 365 is not an exam-notes course."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 10
 * AI / META OUTPUT
 * ------------------------------------------------------------
 */

function checkAIMeta(
  generated,
  errors
) {
  const serialized =
    JSON.stringify(generated)
      .toLowerCase();

  for (const phrase of AI_META_PHRASES) {
    if (
      serialized.includes(
        phrase.toLowerCase()
      )
    ) {
      addError(
        errors,
        `AI/meta language detected: "${phrase}"`
      );
    }
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 11
 * ARTIFICIAL OPENING
 * ------------------------------------------------------------
 */

function checkOpening(
  generated,
  errors,
  warnings
) {
  if (!isObject(generated.lesson)) {
    return;
  }

  const opening =
    normalize(
      generated.lesson.opening
    );

  const weakOpenings = [
    "ఈ రోజు మనం",
    "ఈ పాఠంలో మనం",
    "ఈ రోజు మనం తెలుసుకుందాం",
    "ఈ పాఠంలో తెలుసుకుందాం",
    "ఈ రోజు మనం నేర్చుకోబోతున్నాం",
    "మనము ఈ రోజు"
  ];

  for (const phrase of weakOpenings) {
    if (
      opening.startsWith(
        normalize(phrase)
      )
    ) {
      addWarning(
        warnings,
        `Opening uses a generic classroom-style beginning: "${phrase}"`
      );

      break;
    }
  }

  /*
   * Opening should not be just one tiny sentence.
   */

  if (opening.length < 80) {
    addError(
      errors,
      "Opening is too short to establish the human importance of the topic."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 12
 * HUMAN RELEVANCE
 * ------------------------------------------------------------
 */

function checkHumanRelevance(
  generated,
  errors,
  warnings
) {
  if (!isObject(generated.lesson)) {
    return;
  }

  const relevantFields = [
    "why_it_matters",
    "real_life_example",
    "what_it_means_for_me",
    "takeaway"
  ];

  const combined =
    relevantFields
      .map(field =>
        generated.lesson[field] || ""
      )
      .join("\n");

  const humanTerms = [
    "మన",
    "ప్రజ",
    "పౌర",
    "జీవితం",
    "రోజువారీ",
    "సమాజం",
    "కుటుంబం",
    "వ్యక్తి",
    "హక్కు",
    "బాధ్యత"
  ];

  const matches =
    humanTerms.filter(
      term =>
        combined.includes(term)
    ).length;

  if (matches < 2) {
    addWarning(
      warnings,
      "Human-life relevance appears weak."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 13
 * PARAGRAPH READABILITY
 * ------------------------------------------------------------
 */

function checkReadability(
  generated,
  warnings
) {
  if (!isObject(generated.lesson)) {
    return;
  }

  for (const field of LESSON_FIELDS) {
    const text =
      generated.lesson[field];

    if (
      typeof text !== "string" ||
      !text.trim()
    ) {
      continue;
    }

    const sentences =
      splitSentences(text);

    if (sentences.length === 0) {
      continue;
    }

    /*
     * Warn about extremely long sentences.
     *
     * This is a warning rather than a hard failure because
     * Telugu sentence length varies naturally.
     */

    const longSentences =
      sentences.filter(
        sentence =>
          sentence.length > 350
      );

    if (
      longSentences.length >= 2
    ) {
      addWarning(
        warnings,
        `lesson.${field} contains several very long sentences.`
      );
    }
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 14
 * SIMPLE COMPARISON
 * ------------------------------------------------------------
 */

function checkComparison(
  generated,
  errors,
  warnings
) {
  const text =
    generated.lesson &&
    generated.lesson.simple_comparison;

  if (
    typeof text !== "string" ||
    !text.trim()
  ) {
    addError(
      errors,
      "simple_comparison is required."
    );

    return;
  }

  /*
   * We don't require a literal "like" phrase because
   * some constitutional topics are better explained
   * through a direct comparison.
   */

  if (text.trim().length < 60) {
    addWarning(
      warnings,
      "Simple comparison may be too brief to be useful."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 15
 * WHAT IT MEANS FOR ME
 * ------------------------------------------------------------
 */

function checkPersonalMeaning(
  generated,
  errors
) {
  const text =
    generated.lesson &&
    generated.lesson.what_it_means_for_me;

  if (
    typeof text !== "string" ||
    !text.trim()
  ) {
    addError(
      errors,
      "what_it_means_for_me is required."
    );

    return;
  }

  const personalIndicators = [
    "మీరు",
    "మనకు",
    "పౌరుడిగా",
    "పౌరురాలిగా",
    "మన జీవితంలో",
    "మీ జీవితంలో",
    "ప్రజగా"
  ];

  const hasPersonalMeaning =
    personalIndicators.some(
      phrase =>
        text.includes(phrase)
    );

  if (!hasPersonalMeaning) {
    addError(
      errors,
      "what_it_means_for_me does not clearly connect the lesson to the reader."
    );
  }
}


/*
 * ------------------------------------------------------------
 * SECTION 16
 * QUALITY SCORE
 * ------------------------------------------------------------
 *
 * Score is supplementary.
 *
 * A lesson fails based on hard errors first.
 * The score helps us understand how strong a passing lesson is.
 * ------------------------------------------------------------
 */

function calculateScore(
  generated
) {
  if (
    !generated ||
    !isObject(generated.lesson)
  ) {
    return 0;
  }

  let score = 100;

  const combined =
    LESSON_FIELDS
      .map(field =>
        generated.lesson[field] || ""
      )
      .join("\n");

  const totalLength =
    combined.trim().length;

  if (totalLength < 1200) {
    score -= 8;
  }

  if (totalLength > 25000) {
    score -= 5;
  }

  const ratio =
    teluguRatio(combined);

  if (ratio < 0.60) {
    score -= 10;
  }

  if (ratio < 0.50) {
    score -= 10;
  }

  const duplicates =
    getDuplicateSentences(combined);

  score -=
    duplicates.length * 8;

  let genericCount = 0;

  for (const phrase of GENERIC_PHRASES) {
    genericCount +=
      countOccurrences(
        combined,
        phrase
      );
  }

  score -=
    Math.min(
      genericCount * 3,
      15
    );

  return Math.max(
    0,
    Math.min(100, score)
  );
}


/*
 * ------------------------------------------------------------
 * MAIN QUALITY CHECK
 * ------------------------------------------------------------
 */

function checkQuality({
  generated,
  syllabus
}) {
  const errors = [];
  const warnings = [];

  if (!isObject(generated)) {
    return {
      valid: false,
      score: 0,
      errors: [
        "Generated lesson must be an object."
      ],
      warnings: []
    };
  }

  if (!isObject(syllabus)) {
    return {
      valid: false,
      score: 0,
      errors: [
        "Syllabus entry is missing or invalid."
      ],
      warnings: []
    };
  }

  checkLessonStructure(
    generated,
    errors,
    warnings
  );

  checkOverallLength(
    generated,
    errors,
    warnings
  );

  checkTelugu(
    generated,
    errors,
    warnings
  );

  checkRealLifeExample(
    generated,
    errors,
    warnings
  );

  checkMisunderstanding(
    generated,
    errors,
    warnings
  );

  checkTakeaway(
    generated,
    errors,
    warnings
  );

  checkRepetition(
    generated,
    errors,
    warnings
  );

  checkGenericContent(
    generated,
    errors,
    warnings
  );

  checkExamStyle(
    generated,
    errors,
    warnings
  );

  checkAIMeta(
    generated,
    errors
  );

  checkOpening(
    generated,
    errors,
    warnings
  );

  checkHumanRelevance(
    generated,
    errors,
    warnings
  );

  checkReadability(
    generated,
    warnings
  );

  checkComparison(
    generated,
    errors,
    warnings
  );

  checkPersonalMeaning(
    generated,
    errors
  );

  const score =
    calculateScore(
      generated
    );

  /*
   * A score below 70 means the lesson is not good enough
   * even if the structural validator happened to pass.
   */

  if (score < 70) {
    addError(
      errors,
      `Editorial quality score is too low: ${score}/100.`
    );
  }

  return {
    valid: errors.length === 0,
    score,
    errors,
    warnings
  };
}


/*
 * ------------------------------------------------------------
 * CLI MODE
 * ------------------------------------------------------------
 *
 * Usage:
 *
 * node scripts/quality-check.js data/day-001.json
 * ------------------------------------------------------------
 */

function loadJson(filePath) {
  const absolutePath =
    path.resolve(filePath);

  if (!fs.existsSync(absolutePath)) {
    throw new Error(
      `File not found: ${absolutePath}`
    );
  }

  const text =
    fs.readFileSync(
      absolutePath,
      "utf8"
    );

  try {
    return JSON.parse(text);
  } catch (error) {
    throw new Error(
      `Invalid JSON in ${absolutePath}: ${error.message}`
    );
  }
}


function findSyllabusEntry(
  syllabusFile,
  day
) {
  if (Array.isArray(syllabusFile)) {
    return syllabusFile.find(
      item =>
        Number(item.day) === day
    );
  }

  if (
    isObject(syllabusFile) &&
    Array.isArray(syllabusFile.days)
  ) {
    return syllabusFile.days.find(
      item =>
        Number(item.day) === day
    );
  }

  return null;
}


async function runCli() {
  const generatedPath =
    process.argv[2];

  if (!generatedPath) {
    console.error(
      "Usage: node scripts/quality-check.js <generated-json>"
    );

    process.exit(1);
  }

  const generated =
    loadJson(generatedPath);

  const day =
    Number(generated.day);

  if (
    !Number.isInteger(day) ||
    day < 1 ||
    day > 365
  ) {
    console.error(
      "Invalid day in generated lesson."
    );

    process.exit(1);
  }

  const syllabusPath =
    path.resolve(
      __dirname,
      "..",
      "data",
      "syllabus.json"
    );

  const syllabusFile =
    loadJson(syllabusPath);

  const syllabus =
    findSyllabusEntry(
      syllabusFile,
      day
    );

  if (!syllabus) {
    console.error(
      `Could not find day ${day} in syllabus.json`
    );

    process.exit(1);
  }

  const result =
    checkQuality({
      generated,
      syllabus
    });

  console.log(
    "\n=========================================="
  );

  console.log(
    `CONSTITUTION 365 QUALITY CHECK — DAY ${day}`
  );

  console.log(
    "==========================================\n"
  );

  console.log(
    `QUALITY SCORE: ${result.score}/100`
  );

  console.log(
    `STATUS: ${result.valid ? "PASS" : "FAIL"}`
  );

  if (result.errors.length > 0) {
    console.log("\nERRORS:");

    for (const error of result.errors) {
      console.log(`  ✗ ${error}`);
    }
  }

  if (result.warnings.length > 0) {
    console.log("\nWARNINGS:");

    for (const warning of result.warnings) {
      console.log(`  ! ${warning}`);
    }
  }

  console.log("");

  if (!result.valid) {
    process.exit(1);
  }
}


/*
 * ------------------------------------------------------------
 * EXPORTS
 * ------------------------------------------------------------
 */

module.exports = {
  checkQuality,
  calculateScore
};


if (require.main === module) {
  runCli().catch(error => {
    console.error(
      `\nQUALITY CHECK ERROR: ${error.message}`
    );

    process.exit(1);
  });
}
